version: '3.3'

services:
   db:
     image: mysql:5.7
     ports:
      - "9944:3306"
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: "root"
       MYSQL_DATABASE: "<DATABASE_NAME>"
       MYSQL_USER: "root"
       MYSQL_PASSWORD: "root"

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "9945:80"
     volumes:
       - ./:/var/www/html/wp-content/themes/<THEME_NAME>
     restart: always
     environment:
       WORDPRESS_DB_HOST: "db:3306"
       WORDPRESS_DB_USER: "root"
       WORDPRESS_DB_PASSWORD: "root"
       WORDPRESS_DB_NAME: "<DATABASE_NAME>"
volumes:
    db_data: {}
